# Generated by Django 5.2.4 on 2025-08-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='uint_price',
            new_name='unit_price',
        ),
    ]
