# Generated by Django 5.2.4 on 2025-08-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_uint_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'price', 'inventory']},
        ),
    ]
