# Generated by Django 5.2.5 on 2025-08-14 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='min length is one', regex='\\W+')]),
        ),
    ]
