# Generated by Django 5.2.5 on 2025-08-14 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='min length is one', regex='[a-zA-Z0-9]+')]),
        ),
    ]
